################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../mkstemp.c \
../zip_add.c \
../zip_add_dir.c \
../zip_close.c \
../zip_delete.c \
../zip_dirent.c \
../zip_discard.c \
../zip_entry_free.c \
../zip_entry_new.c \
../zip_err_str.c \
../zip_error.c \
../zip_error_clear.c \
../zip_error_get.c \
../zip_error_get_sys_type.c \
../zip_error_strerror.c \
../zip_error_to_str.c \
../zip_fclose.c \
../zip_fdopen.c \
../zip_file_error_clear.c \
../zip_file_error_get.c \
../zip_file_get_offset.c \
../zip_file_strerror.c \
../zip_filerange_crc.c \
../zip_fopen.c \
../zip_fopen_encrypted.c \
../zip_fopen_index.c \
../zip_fopen_index_encrypted.c \
../zip_fread.c \
../zip_get_archive_comment.c \
../zip_get_archive_flag.c \
../zip_get_compression_implementation.c \
../zip_get_encryption_implementation.c \
../zip_get_file_comment.c \
../zip_get_file_extra.c \
../zip_get_name.c \
../zip_get_num_entries.c \
../zip_get_num_files.c \
../zip_memdup.c \
../zip_name_locate.c \
../zip_new.c \
../zip_open.c \
../zip_rename.c \
../zip_replace.c \
../zip_set_archive_comment.c \
../zip_set_archive_flag.c \
../zip_set_default_password.c \
../zip_set_file_comment.c \
../zip_set_file_compression.c \
../zip_set_file_extra.c \
../zip_set_name.c \
../zip_source_buffer.c \
../zip_source_close.c \
../zip_source_crc.c \
../zip_source_deflate.c \
../zip_source_error.c \
../zip_source_file.c \
../zip_source_filep.c \
../zip_source_free.c \
../zip_source_function.c \
../zip_source_layered.c \
../zip_source_open.c \
../zip_source_pkware.c \
../zip_source_pop.c \
../zip_source_read.c \
../zip_source_stat.c \
../zip_source_window.c \
../zip_source_zip.c \
../zip_source_zip_new.c \
../zip_stat.c \
../zip_stat_index.c \
../zip_stat_init.c \
../zip_strerror.c \
../zip_unchange.c \
../zip_unchange_all.c \
../zip_unchange_archive.c \
../zip_unchange_data.c \
../zip_utf-8.c 

OBJS += \
./mkstemp.o \
./zip_add.o \
./zip_add_dir.o \
./zip_close.o \
./zip_delete.o \
./zip_dirent.o \
./zip_discard.o \
./zip_entry_free.o \
./zip_entry_new.o \
./zip_err_str.o \
./zip_error.o \
./zip_error_clear.o \
./zip_error_get.o \
./zip_error_get_sys_type.o \
./zip_error_strerror.o \
./zip_error_to_str.o \
./zip_fclose.o \
./zip_fdopen.o \
./zip_file_error_clear.o \
./zip_file_error_get.o \
./zip_file_get_offset.o \
./zip_file_strerror.o \
./zip_filerange_crc.o \
./zip_fopen.o \
./zip_fopen_encrypted.o \
./zip_fopen_index.o \
./zip_fopen_index_encrypted.o \
./zip_fread.o \
./zip_get_archive_comment.o \
./zip_get_archive_flag.o \
./zip_get_compression_implementation.o \
./zip_get_encryption_implementation.o \
./zip_get_file_comment.o \
./zip_get_file_extra.o \
./zip_get_name.o \
./zip_get_num_entries.o \
./zip_get_num_files.o \
./zip_memdup.o \
./zip_name_locate.o \
./zip_new.o \
./zip_open.o \
./zip_rename.o \
./zip_replace.o \
./zip_set_archive_comment.o \
./zip_set_archive_flag.o \
./zip_set_default_password.o \
./zip_set_file_comment.o \
./zip_set_file_compression.o \
./zip_set_file_extra.o \
./zip_set_name.o \
./zip_source_buffer.o \
./zip_source_close.o \
./zip_source_crc.o \
./zip_source_deflate.o \
./zip_source_error.o \
./zip_source_file.o \
./zip_source_filep.o \
./zip_source_free.o \
./zip_source_function.o \
./zip_source_layered.o \
./zip_source_open.o \
./zip_source_pkware.o \
./zip_source_pop.o \
./zip_source_read.o \
./zip_source_stat.o \
./zip_source_window.o \
./zip_source_zip.o \
./zip_source_zip_new.o \
./zip_stat.o \
./zip_stat_index.o \
./zip_stat_init.o \
./zip_strerror.o \
./zip_unchange.o \
./zip_unchange_all.o \
./zip_unchange_archive.o \
./zip_unchange_data.o \
./zip_utf-8.o 

C_DEPS += \
./mkstemp.d \
./zip_add.d \
./zip_add_dir.d \
./zip_close.d \
./zip_delete.d \
./zip_dirent.d \
./zip_discard.d \
./zip_entry_free.d \
./zip_entry_new.d \
./zip_err_str.d \
./zip_error.d \
./zip_error_clear.d \
./zip_error_get.d \
./zip_error_get_sys_type.d \
./zip_error_strerror.d \
./zip_error_to_str.d \
./zip_fclose.d \
./zip_fdopen.d \
./zip_file_error_clear.d \
./zip_file_error_get.d \
./zip_file_get_offset.d \
./zip_file_strerror.d \
./zip_filerange_crc.d \
./zip_fopen.d \
./zip_fopen_encrypted.d \
./zip_fopen_index.d \
./zip_fopen_index_encrypted.d \
./zip_fread.d \
./zip_get_archive_comment.d \
./zip_get_archive_flag.d \
./zip_get_compression_implementation.d \
./zip_get_encryption_implementation.d \
./zip_get_file_comment.d \
./zip_get_file_extra.d \
./zip_get_name.d \
./zip_get_num_entries.d \
./zip_get_num_files.d \
./zip_memdup.d \
./zip_name_locate.d \
./zip_new.d \
./zip_open.d \
./zip_rename.d \
./zip_replace.d \
./zip_set_archive_comment.d \
./zip_set_archive_flag.d \
./zip_set_default_password.d \
./zip_set_file_comment.d \
./zip_set_file_compression.d \
./zip_set_file_extra.d \
./zip_set_name.d \
./zip_source_buffer.d \
./zip_source_close.d \
./zip_source_crc.d \
./zip_source_deflate.d \
./zip_source_error.d \
./zip_source_file.d \
./zip_source_filep.d \
./zip_source_free.d \
./zip_source_function.d \
./zip_source_layered.d \
./zip_source_open.d \
./zip_source_pkware.d \
./zip_source_pop.d \
./zip_source_read.d \
./zip_source_stat.d \
./zip_source_window.d \
./zip_source_zip.d \
./zip_source_zip_new.d \
./zip_stat.d \
./zip_stat_index.d \
./zip_stat_init.d \
./zip_strerror.d \
./zip_unchange.d \
./zip_unchange_all.d \
./zip_unchange_archive.d \
./zip_unchange_data.d \
./zip_utf-8.d 


# Each subdirectory must supply rules for building sources it contributes
%.o: ../%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -DHAVE_UNISTD_H -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


